services:
  # Backend Service
  - type: web
    name: saas-backend
    env: node
    repo: https://github.com/Salmonnaik/Accredian.git
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
    healthCheckPath: /health
    autoDeploy: true
