name: saas-backend
services:
- name: backend
  source_dir: /backend
  github:
    repo: Salmonnaik/Accredian
    branch: master
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  env:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: 5000
  http_port: 5000
  routes:
  - path: /api
